version: '3.6'

services:
  ogcproxy:
    build: .
    image: ogcproxy
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_CONTEXT_PATH=${SERVER_CONTEXT_PATH}
      - WQP_GEOSERVER_HOST=${WQP_GEOSERVER_HOST}
      - WQP_GEOSERVER_PASSWORD=${WQP_GEOSERVER_PASSWORD}
      - WQP_LAYERBUILDER_URL=${WQP_LAYERBUILDER_URL}
      - LAYERBUILDER_WORKING_DIR=/data/working
      - LAYERBUILDER_SHAPEFILES_DIR=/data/shapefiles
