version: '3.3'

services:
  ogcproxy:
    build: .
    image: ogcproxy
    ports:
      - "8080:8080"
    environment:
      - WQP_GEOSERVER_PASSWORD=${WQP_GEOSERVER_PASSWORD}
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_CONTEXT_PATH=${SERVER_CONTEXT_PATH}
      - WQP_LAYERBUILDER_HOST=${WQP_LAYERBUILDER_HOST}
      - WQP_GEOSERVER_HOST=${WQP_GEOSERVER_HOST}
