projectName: "wqp-external"
applicationName: "ogcproxy"
dockerImageName: "ogcproxy"
containerPort: 8080
artifactoryPath: "wqp"
gitRepoUrl: "https://github.com/NWQMC/ogcproxy.git"
gitRepoCredentialsId: "Jenkins-GitHub-Read-Write-Token"
memory: 1024
healthCheck: "/ogcservices/actuator/health"
deployJobName: "ogcproxy-container-deploy"
# configuration repository paths
configRepoPath: "wma/docker/wqp/ogcproxy"
configCredentialsId: "wma-eto-eb-rsa"
# configure routing
urlRules:
  - type: forward
    conditions:
      - "/ogcservices/*"
    priority: 88
