projectName: "wqp_external"
applicationName: "ogcproxy"
dockerImageName: "ogcproxy"
containerPort: 8080
artifactoryPath: "wqp"
gitlabPath: "wma/docker/wqp"
gitRepoUrl: "https://github.com/NWQMC/ogcproxy.git"
gitRepoCredentialsId: "GITHUB_ACCESS_TOKEN"
repoPath: "NWQMC/ogcproxy"
memory: 768
rulePriority: 88
healthCheck: "/actuator/health"
contextPath: "/ogcproxy/*"
deployJobName: "ogcproxy-container-deploy"