---
spring:
  application:
    name: ogcproxy
  jmx:
    default-domain: ogcproxy
management:
  info:
    git:
      mode: full

server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH}

# WQP GeoServer settings
wqp:
  geoserver:
    host: ${WQP_GEOSERVER_HOST}
    workspace: wqp_sites
    user: admin
    pass: ${WQP_GEOSERVER_PASSWORD}
    catchup:
      time: 1000
  layerbuilder:
    url: ${WQP_LAYERBUILDER_URL}


layerbuilder:
  dir:
    working: ${LAYERBUILDER_WORKING_DIR}
    shapefiles: ${LAYERBUILDER_SHAPEFILES_DIR}

# Proxy Service Properties
proxy:
  thread:
    sleep: 500
  readLock:
    timout: 30
  writedLock:
    timout: 120
